# Generated by Django 3.2.4 on 2021-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210604_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
