# Generated by Django 3.2.4 on 2021-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_gallery_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='gallery_picture',
            name='published',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
